alerts/urls.py
from django.urls import path

from .views import lead_company, set_alert

app_name = "alerts"

urlpatterns = []

htmx_patterns = [
    path("set_alert/", set_alert, name="set_alert"),
    path("lead_company/", lead_company, name="lead_company"),
]

urlpatterns += htmx_patterns

app/urls.py
from django.urls import path

from .views import companies, index

app_name = "app"
urlpatterns = [
    path("", index, name="index"),
    path("companies", companies, name="companies"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("app.urls")),
    path("alerts/", include("alerts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

alerts/models.py
from django.db.models import CharField, EmailField, URLField

from commons.models import TimeStampedModel


class AlertEmail(TimeStampedModel):
    email = EmailField(unique=True)

    def __str__(self):
        return f"{self.email}"


class CompanyEmail(TimeStampedModel):
    company_name = CharField(max_length=100)
    email = EmailField(unique=True)
    url = URLField()
    country = CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.company_name} - {self.email} ({self.country})"

app/models.py
from django.db import models

# Create your models here.

commons/models.py
from django.db.models import DateTimeField, Model


class TimeStampedModel(Model):
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    class Meta:
        abstract = True

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

alerts/views.py
from django.http import HttpRequest, HttpResponse

from .models import AlertEmail, CompanyEmail


def set_alert(request: HttpRequest):
    email = request.POST.get("email", None)
    if email is None or email.strip() == "":
        return HttpResponse(
            '<p class="text-center text-error">:( Please provide an email address.</p>'
        )

    _, _ = AlertEmail.objects.get_or_create(email=email)

    return HttpResponse(
        '<p class="text-center text-success">We&apos;ll contact you soon!</p>'
    )


def lead_company(request: HttpRequest):
    company_name = request.POST.get("company_name", None)
    email = request.POST.get("email", None)
    company_url = request.POST.get("company_url", None)
    country = request.POST.get("country", None)

    if company_name is None or company_name.strip() == "":
        return HttpResponse(
            '<p class="text-center text-error">:( Please provide your company name.</p>'
        )
    if email is None or email.strip() == "":
        return HttpResponse(
            '<p class="text-center text-error">:( Please provide your email address.</p>'
        )
    if company_url is None or company_url.strip() == "":
        return HttpResponse(
            '<p class="text-center text-error">:( Please provide your company URL.</p>'
        )
    if country is None or country.strip() == "":
        return HttpResponse(
            '<p class="text-center text-error">:( Please provide your country or location.</p>'
        )

    _, _ = CompanyEmail.objects.get_or_create(
        email=email,
        defaults={
            "company_name": company_name,
            "email": email,
            "url": company_url,
            "country": country,
        },
    )

    return HttpResponse(
        '<p class="text-center text-success">We&apos;ll contact you soon!</p>'
    )

app/views.py
from django.shortcuts import render


def index(request):
    print(request.htmx)
    context = {"world": "world"}
    return render(request, "app/index.html", context)


def companies(request):
    print(request.htmx)
    context = {}
    return render(request, "app/companies_leads.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}AI Careers Hub{% endblock %}</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'images/icon.png' %}"
    />
    <!-- TAILWIND -->
    <link rel="stylesheet" href="{% static 'css/output.css' %}" />
    <!-- DJANGO-HTMX -->
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <!-- DAISY UI -->
    <link
      href="{% static 'css/daisyui.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <script src="{% static 'js/daisyui.min.js' %}"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/general.css' %}" />
  </head>
  <body class="px-2 sm:px-6 md:px-8">
    <header>
      <div class="navbar bg-base-100 min-w-[350px]">
        <div class="navbar-start">
          <a href="{% url 'app:index' %}" class="btn btn-ghost text-xl"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-brain-circuit"
            >
              <path
                d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"
              />
              <path d="M9 13a4.5 4.5 0 0 0 3-4" />
              <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
              <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
              <path d="M6 18a4 4 0 0 1-1.967-.516" />
              <path d="M12 13h4" />
              <path d="M12 18h6a2 2 0 0 1 2 2v1" />
              <path d="M12 8h8" />
              <path d="M16 8V5a2 2 0 0 1 2-2" />
              <circle cx="16" cy="13" r=".5" />
              <circle cx="18" cy="3" r=".5" />
              <circle cx="20" cy="21" r=".5" />
              <circle cx="20" cy="8" r=".5" />
            </svg>
            AI Careers Hub</a
          >
        </div>

        <div class="navbar-end">
          <a href="{% url 'app:companies' %}" class="btn btn-info text-base-100"
            >Hire with us</a
          >
        </div>
      </div>
    </header>
    <main>
      {% block content %}
      <!-- Your page-specific content goes here -->
      {% endblock %}
    </main>
    <footer></footer>
    <script src="{% static 'js/alpine.min.js' %}" defer></script>
  </body>
</html>

app/templates/app/companies_leads.html
{% extends 'app/base.html' %} {% block content %}
<div class="my-10">
  <h1 class="text-3xl font-bold text-center">Hire with us</h1>
  <p class="text-medium text-center">
    We'll promote your open positions and <br />
    contact for you the top talent in AI.
  </p>
  <form
    hx-post="{% url 'alerts:lead_company' %}"
    hx-target="#hire_result"
    method="post"
    class="flex flex-col justify-center"
    hx-disabled-elt="button"
  >
    {% csrf_token %}
    <label class="form-control w-full max-w-xs mx-auto">
      <div class="label">
        <span class="label-text">Company</span>
      </div>
      <input
        type="text"
        name="company_name"
        placeholder="My Company"
        class="input input-bordered input-primary w-full max-w-xs"
      />
    </label>
    <label class="form-control w-full max-w-xs mx-auto">
      <div class="label">
        <span class="label-text">Email</span>
      </div>
      <input
        type="email"
        name="email"
        placeholder="company@ai.com"
        class="input input-bordered input-primary w-full max-w-xs"
      />
    </label>
    <label class="form-control w-full max-w-xs mx-auto">
      <div class="label">
        <span class="label-text">Company URL</span>
      </div>
      <input
        type="text"
        name="company_url"
        placeholder="https://mycompany.com"
        class="input input-bordered input-primary w-full max-w-xs"
      />
    </label>
    <label class="form-control w-full max-w-xs mx-auto">
      <div class="label">
        <span class="label-text">Country</span>
      </div>
      <input
        type="text"
        name="country"
        placeholder="United States, Mexico..."
        class="input input-bordered input-primary w-full max-w-xs"
      />
    </label>
    <button class="btn btn-info text-base-100 mx-auto my-4">
      <span class="loading loading-spinner loading-xs my-indicator"></span>
      Start Hiring
    </button>
  </form>
  <div id="hire_result" class="flex justify-center py-2"></div>
</div>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %} {% block content %}
<div class="my-20">
  <h1 class="text-3xl font-bold text-center">
    Find the best jobs in AI industry
  </h1>
  <p class="text-medium text-center">
    Get hired in a next generation AI company right now.
  </p>
  <form
    hx-post="{% url 'alerts:set_alert' %}"
    hx-target="#alert_result"
    method="post"
    class="flex flex-col justify-center gap-y-4"
    hx-disabled-elt="button"
  >
    {% csrf_token %}
    <label class="form-control w-full max-w-xs mx-auto">
      <div class="label">
        <span class="label-text">Receive job alerts on your email</span>
      </div>
      <input
        type="email"
        name="email"
        placeholder="success@getajob.com"
        class="input input-bordered input-primary w-full max-w-xs"
      />
    </label>
    <button class="btn btn-info text-base-100 mx-auto">
      <span class="loading loading-spinner loading-xs my-indicator"></span>
      Subscribe
    </button>
  </form>
  <div id="alert_result" class="flex justify-center py-2"></div>
</div>

{% endblock %}